### ISSUE TITLE
After some minutes running, clicking a button triggers an action multiple times

### ISSUE THREAD

**Issue by salazarbarrera** [ddgond/uebersicht-grid-launcher#1]
I know this is probably totally not maintained, but while using it I found a bug and I wanted to contribute.

It turns out that with every refresh, each action is added again to the event handler of each button, on top of the previous action  (at least in M1 Monterrey with Übersicht 1.6). So, after 30 seconds, the widget became unusable. A small fix is just turning off the handlers during the refresh.

**Comment by ddgond** [comment]
You're right, this isn't maintained, I've almost forgotten it even existed! I'll merge that change in, thanks!
